### ISSUE TITLE
Vassar Stanford tokenizer gets bad payload

### ISSUE THREAD

**Issue by nancyide** [lapps/org.lappsgrid.all#13]
Note the first part of the payload from the Vassar Stanford sentence splitter:
{"discriminator":"http://vocab.lappsgrid.org/ns/media/jsonld#lif","payload":{"@context":"http://vocab.lappsgrid.org/context-1.0.0.jsonld","metadata":{},"text":{"@value":"{@value=\n\n\n\nFarming on Sand:

**Comment by ksuderman** [comment]
This issue has been moved [here](https://github.com/oanc/org.anc.lapps.stanford/issues/11).
