### ISSUE TITLE
Harmonize version numbers

### ISSUE THREAD

**Issue by ksuderman** [lapps/org.lappsgrid.all#15]
Currently each Lappsgrid module is versioned independently which makes if difficult to know what versions of a module to use.

**Question** Should the next release harmonize the module versions so they all use the same version number (2.6.0)?

**Pros**

1. Easy to remember what version of a module to use.

**Cons**

1. A simple fix to one module requires that every module be updated (at least the version in the pom.xml) and redeployed to Maven Central; a non-trivial undertaking.
1. Modules that have not changed will have their version number increased.  For example, the *api* module is still at version 2.0.1 indicating that it is very stable.

**Modules**

- [ ] parent-pom
- [ ] war-parent-pom
- [ ] all
- [ ] api
- [ ] core
- [ ] client
- [ ] discriminator
- [ ] serialization
- [ ] annotations
- [ ] metadata
- [ ] vocabulary

**Comment by keighrim** [comment]
Adding my $.02, I don't think the module versions need to be harmonized as long as they are standalone modules. It just looks like too much hassle for a small achievement.

**Comment by marcverhagen** [comment]
And here are my 1/50th of a dollar...

There is some benefit to harmonization but the cons far outweigh the pros. To me it is natural to have to worry about what versions you need in an overall release versus freaking out that some version of the code actually has several versions.

Given that con #1 is non-trivial this is a dead end to me.

Git has the notion of submodules and we could use that for this, but Git's submodules do have a not so nice reek to them in my opinion.

**Comment by ksuderman** [comment]
Ok, it sounds like this is a bad idea and not worth doing.
