### ISSUE TITLE
2.5.0

### ISSUE THREAD

**Issue by ksuderman** [lapps/org.lappsgrid.all#16]
For some reason the deploy.sh script is not longer producing all the artifacts requires to make oss.sontatype.org happy.

**Comment by keighrim** [comment]
Just wanted to follow up on this. Is there any update?

**Comment by ksuderman** [comment]
No. But since GitHub found a security problem (jackson-databind) in our parent pom we will have to roll out another release soon.

**Comment by ksuderman** [comment]
The org.lappsgrid:all:2.5.0:pom module is now available on Maven Central.  

**Note** The module uses *pom* packaging.

```xml
<dependency>
    <groupId>org.lappsgrid</groupId>
    <artifactId>all</artifactId>
    <version>2.5.0</version>
    <packaging>pom</packaging>
</dependency>
```
