### ISSUE TITLE
Error with 2.1.0

### ISSUE THREAD

**Issue by keighrim** [lapps/org.lappsgrid.all#3]
After I updated POM in Brandeis services to use org.lappsgrid.all 2.1.0, I'm getting this error when compiling.

`Features is not public in org.lappsgrid.vocabulary; cannot be accessed from outside package`

**Comment by ksuderman** [comment]
Copy and paste error when updating the Features class...

**Comment by ksuderman** [comment]
Oops, a copy/paste error when updating the Features class.

**Comment by ksuderman** [comment]
org.lappsgrid:all:2.1.1 contains the fixes.
