### ISSUE TITLE
How can I set up a local instance of lappsgrid?

### ISSUE THREAD

**Issue by qiuwei** [lapps/org.lappsgrid.all#5]
I have a few questions about lappsgrid.
1. How can I set up a local instance of lappsgrid?
 I find a lot of webservice who acts as wrapper for various NLP tools? But how can I put them into Galaxy? If I understand it correctly, I need some tool definition files for Galaxy.
1. Is there any underlying modification made to Galaxy? Or are just the tools swapped?
2. I have difficulties in understanding the function of the  LAPPS WS-EV. Is it used to describe the metadata of webservices, such as what annotation the input and output contain? But I saw caveats which claim that lappsgrid cannot guarantee that the document to be processed contains the required annotation types.

BTW, I couldn't find any link to the mailing list on the website. Sorry for asking general questions here.

Thanks in advance.

**Comment by ksuderman** [comment]
Responded via private email.  Information about setting up a LAPPS Grid instance will be available on our wiki.
